language: objective-c
env:
    matrix:
    - XCODE_SCHEME="KeyClip iOS" XCODE_SDK=iphonesimulator
    - XCODE_SCHEME="KeyClip Mac" XCODE_SDK=macosx
script: xcodebuild -project KeyClip.xcodeproj -scheme "$XCODE_SCHEME" -sdk $XCODE_SDK -configuration Release build test
osx_image: xcode7.3